"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class double_array_t(object):
    __slots__ = ["num_elements", "double_array"]

    __typenames__ = ["int32_t", "double"]

    __dimensions__ = [None, ["num_elements"]]

    def __init__(self):
        self.num_elements = 0
        self.double_array = []

    def encode(self):
        buf = BytesIO()
        buf.write(double_array_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_elements))
        buf.write(struct.pack('>%dd' % self.num_elements, *self.double_array[:self.num_elements]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != double_array_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return double_array_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = double_array_t()
        self.num_elements = struct.unpack(">i", buf.read(4))[0]
        self.double_array = struct.unpack('>%dd' % self.num_elements, buf.read(self.num_elements * 8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if double_array_t in parents: return 0
        tmphash = (0x3f4b0454e264f52c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if double_array_t._packed_fingerprint is None:
            double_array_t._packed_fingerprint = struct.pack(">Q", double_array_t._get_hash_recursive([]))
        return double_array_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

