"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import rs_lcm.pose_stamped_t

class dual_pose_stamped_t(object):
    __slots__ = ["right_pose", "left_pose"]

    __typenames__ = ["rs_lcm.pose_stamped_t", "rs_lcm.pose_stamped_t"]

    __dimensions__ = [None, None]

    def __init__(self):
        self.right_pose = rs_lcm.pose_stamped_t()
        self.left_pose = rs_lcm.pose_stamped_t()

    def encode(self):
        buf = BytesIO()
        buf.write(dual_pose_stamped_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        assert self.right_pose._get_packed_fingerprint() == rs_lcm.pose_stamped_t._get_packed_fingerprint()
        self.right_pose._encode_one(buf)
        assert self.left_pose._get_packed_fingerprint() == rs_lcm.pose_stamped_t._get_packed_fingerprint()
        self.left_pose._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != dual_pose_stamped_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return dual_pose_stamped_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = dual_pose_stamped_t()
        self.right_pose = rs_lcm.pose_stamped_t._decode_one(buf)
        self.left_pose = rs_lcm.pose_stamped_t._decode_one(buf)
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if dual_pose_stamped_t in parents: return 0
        newparents = parents + [dual_pose_stamped_t]
        tmphash = (0x2783aedef147c69a+ rs_lcm.pose_stamped_t._get_hash_recursive(newparents)+ rs_lcm.pose_stamped_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if dual_pose_stamped_t._packed_fingerprint is None:
            dual_pose_stamped_t._packed_fingerprint = struct.pack(">Q", dual_pose_stamped_t._get_hash_recursive([]))
        return dual_pose_stamped_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

