"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class simple_binary_mask_t(object):
    __slots__ = ["size", "mask"]

    __typenames__ = ["int32_t", "boolean"]

    __dimensions__ = [None, ["size"]]

    def __init__(self):
        self.size = 0
        self.mask = []

    def encode(self):
        buf = BytesIO()
        buf.write(simple_binary_mask_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.size))
        buf.write(struct.pack('>%db' % self.size, *self.mask[:self.size]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != simple_binary_mask_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return simple_binary_mask_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = simple_binary_mask_t()
        self.size = struct.unpack(">i", buf.read(4))[0]
        self.mask = map(bool, struct.unpack('>%db' % self.size, buf.read(self.size)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if simple_binary_mask_t in parents: return 0
        tmphash = (0x829e57a0301a4206) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if simple_binary_mask_t._packed_fingerprint is None:
            simple_binary_mask_t._packed_fingerprint = struct.pack(">Q", simple_binary_mask_t._get_hash_recursive([]))
        return simple_binary_mask_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

